name: Arcade
main: de.plabbabap.arcade.Plugin
version: 1.0
author: Zortax
description: DevAthlon Projekt
commands:
   addspawn:
      description: Spawn in Minispiel hinzufuegen.
      usage: /addspawn <Minispiel>
   setlobby:
      description: Setzt den Lobbyspawn
      usage: /setlobby
   checkpoint:
      description: Fuegt einen Jumpnrun Checkpoint hinzu
      usage: /checkpoint